name: 'Run unit tests.'
on:
  pull_request:    
    branches:
      - master
      - 'releases/*'
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci works properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
    - name: Run L0 tests.
      run: |
        npm install
        npm test  